### ISSUE TITLE
Headphones connected indicator

### ISSUE THREAD

**Issue by fredrikaverpil** [warmsound/crystal-face#101]
Thank you for a really nice watch face!

I don't know if it is possible to create an indicator for whenever wireless headphones are connected... but Garmin's own watch faces supports this so I figured maybe this is possible.

And on that note, maybe it would be better to show a phone icon rather than the current Bluetooth icon (since headphones also connect over Bluetooth)?
Issues/PRs related to this: #73 #76

**Comment by warmsound** [comment]
Thanks for all your recent input!

I've had a look through the API docs, focussing on the CIQ 3.x entries, but I've not had any luck in finding anything that reports whether a bluetooth audio device is paired with the watch. I'll leave this open in case others have input.

Good point about distinguishing between a paired phone and a paired audio device: I'll do something about this shortly.

**Comment by warmsound** [comment]
I've still not had any luck in determining whether a bluetooth audio device is paired with the watch.

Regarding distinguishing paired phone vs. paired audio device, it would be easy to change the former to a phone icon, but looking at several popular watch faces, users appear to expect the current Bluetooth icon when the watch is paired with a phone, so it may be best to leave this as it is for now.

Obviously, once it becomes possible to show a "headphones connected" indicator, then we may have to revisit this.
