### ISSUE TITLE
Weather field not working

### ISSUE THREAD

**Issue by axcro7** [warmsound/crystal-face#109]
On my vivoactive 3 the weather field was never working.
Back when the API key was required it only showed an exclamation mark, now it only shows a grayed out sun symbol.

**Comment by warmsound** [comment]
Hi again :). As per #110, did you uninstall before the latest reinstall? It's possible that the weather data stored on the watch is in an inconsistent state. Do you have both a GPS position (e.g. acquired by starting an activity), and a Bluetooth connection to your phone (for accessing OpenWeatherMap via the internet)?

**Comment by axro7** [comment]
Hi and thank you for the quick reply! 
I didn't uninstall it, I just tapped upgrade on the phone app. 
I did uninstall and reinstall the watchface this morning and after acquiring a GPS position it shows the weather data.
Is this procedure necessary for each upgrade?

**Comment by warmsound** [comment]
It appears the reinstallation procedure is necessary, at least with the current state of Crystal. I'll keep an eye out for hints about why this is necessary, and whether there's anything I can do to reduce the need to reinstall. My hunch is that it is something related to the way settings are stored. Glad things are working for you now.
