### ISSUE TITLE
Fature request: hourly beep

### ISSUE THREAD

**Issue by Zibri** [warmsound/crystal-face#121]
It would be nice (since many people asked garmin and they didn't do it)
to implement a hourly chime like in old casio watches.
Even better if in the settings you could choose the frequency (pitch) and duration.

https://www.youtube.com/watch?v=PEn7C8Z6qVg

**Comment by flyisland** [comment]
@Zibri  which device do you use?

I'm using 645 and it does have an hourly alert, please check `Settings > System > Time > Alerts`

**Comment by Zibri** [comment]
Garmin Fenix 5X

**Comment by warmsound** [comment]
@Zibri, as @flyisland has suggested, your watch already has a built-in hourly alert. Please see the following manual pages:

- https://www8.garmin.com/manuals/webhelp/fenix5x/EN-US/GUID-6895B03A-4D1B-47CC-B0AB-9330A8A031E1.html
- https://www8.garmin.com/manuals/webhelp/fenix5x/EN-US/GUID-E3FEFEA4-EDF3-4257-8D38-DF3C15AEEB8F.html

**Comment by Zibri** [comment]
hahahahha it's typical for a computer expert to do a mistake like this! :D I never read manuals... and when I read Alerts I was thinking they were for steps or heart or other things I don't need. I don't even use it much for fitness but as main watch and for scuba diving here in Sharm El Sheikh! Thanks anyways... I feel stupid now but it's funny :D
