### ISSUE TITLE
Add FR 245/245M support

### ISSUE THREAD

**Issue by dotpyfe** [warmsound/crystal-face#122]
Garmin released a few new devices (45, 245, 945) so it would be nice to get those supported for this excellent watch face, though I'd be most interested in the 245 support :)

**Comment by warmsound** [comment]
Sure! The new devices have been added to the 3.0.11 SDK from 1 May, so I'll make sure the next release is built against this version. This should be coming in the next few days.

**Comment by warmsound** [comment]
Uh-oh, I've just noticed the Forerunner 45 is a new, smaller screen size, so that's going to require some design work. But the other two watches should be good to go.

**Comment by dotpyfe** [comment]
sweet, thank you!

**Comment by ibidani** [comment]
Thanks @warmsound looking forward to see this merged

**Comment by warmsound** [comment]
Sorry for the delay on this, as I've been away for several days, and just catching up on my Garmin work. I notice that FR 245/245M do not support floors climbed, despite supporting CIQ 3.x, so I'll need to make a small adjustment to the default settings for these watches.
