### ISSUE TITLE
Add support for round-208x208 e.g. Forerunner 45

### ISSUE THREAD

**Issue by warmsound** [warmsound/crystal-face#124]
Forerunner 45 was released with SDK 3.0.11. This needs some design work, as the device is a new, smaller round screen size.

**Comment by warmsound** [comment]
CIQ 1.x, no anti-aliased custom fonts, 48kB memory, 8 colours (each R/G/B component `00` or `FF` only). Known issue with `dc.getFontHeight()` (not used in Crystal code).

**Comment by ericliou** [comment]
Thank you for supporting F45 :)

**Comment by warmsound** [comment]
@ericliou No worries, and sorry this has been so long coming. Thanks (everyone) for your patience.
