### ISSUE TITLE
Stair counter

### ISSUE THREAD

**Issue by jeffwash** [warmsound/crystal-face#136]
Hi,

In your screen images, I see the stair counter on the right side.  I don't see this option.  I have a Fenix 3 hr.

**Comment by pakal-org** [comment]
As far as I know, the Fenix 3 (Hr) doesn't count stairs at all ...

**Comment by warmsound** [comment]
Hi @jeffwash,

@pakal-org is right: Fenix 3 series watches do not support this feature at all unfortunately, so I'm unable to offer it in Crystal.

Sorry,

Vince.
