### ISSUE TITLE
Can’t change color.  

### ISSUE THREAD

**Issue by rvelozo** [warmsound/crystal-face#141]
No matter the color selection, the drop down goes back to the top item after saving. The watch is stuck with the blue (top item)

**Comment by warmsound** [comment]
Hi @rvelozo,

This may have been because of a bug in the iOS version of the Garmin Connect mobile app. This bug has now been fixed in the latest version of that app. The newer Connect IQ app was not affected by this bug.

Hope this helps,

Vince.
