### ISSUE TITLE
"Floors climbed" and "Intensity minutes" options aren't available as meters

### ISSUE THREAD

**Issue by isaburov** [warmsound/crystal-face#146]
Hello, warmsound

Your Crystal WatchFace is great, i am very interested in using it. But i have some problems.

I can't select "Floors climbed" and "Intensity minutes" as configurable meters in settings for your watch face. These options aren't available for my device (fenix 3 HR, software is up to date — Version 5.40.0.0, Serial Number: 4MR109327, your app version 2.3.5). Available options: steps, battery, calories, off.

At the same time I can't use "Floors climbed" in others watch faces. May be the reason of problem in my device, but — can you help solve this problem please? I can pay for your support.

**Comment by warmsound** [comment]
Hi isaburov,

I'm afraid this is a limitation of all Fenix 3 devices: they do not support floors or intensity minutes, at least not in third-party apps, so I'm unable to provide those options for you in Crystal. Sorry about that.

Please let me know if you have any questions about this.

Thanks,

Vince.
