### ISSUE TITLE
Bluettooth always shows connected

### ISSUE THREAD

**Issue by h2soft-de** [warmsound/crystal-face#150]
Since the update to 4.90 on the vivoactive 3 Music, Bluetooth always displays connected, even if it cannot be connected at all. After a restart, it correctly displays disconnected and shows the connection again when the phone is close again. But not the other way around.

**Comment by h2soft-de** [comment]
https://forums.garmin.com/developer/connect-iq/i/bug-reports/vivoactive-3-phoneconnected-always-true

so garmin ist working on it.

**Comment by warmsound** [comment]
Thanks for letting me know about this.
