### ISSUE TITLE
How to set watchface language? 

### ISSUE THREAD

**Issue by XAKEPEHOK** [warmsound/crystal-face#169]
Hi! My vivoactive 3 has russian weekdays and month names at watchface on my old phone, but after pairing watches to another phone its reset to english.
How can I set Russian language for your watchface? Please, help

**Comment by warmsound** [comment]
Hi @XAKEPEHOK, sorry for the long delay. Hopefully you've got to the bottom of this by now. For reference, you can change device language within the Garmin Connect app: from the **Settings** screen for the device, go **Device Settings > System > Language**, select the required language, then **sync** the device. The new language should then be shown on the watchface.
