### ISSUE TITLE
Not Working on Rey Watch

### ISSUE THREAD

**Issue by bowpay** [warmsound/crystal-face#172]
We have both the Rey Star Wars Watch and Captain Marvel.  I believe they are the same watch but the Rey version is not available in the app store.  Works great on Captain Marvel.  Can you easily add support for the watch?  I also don't mind testing to verify it working.

**Comment by warmsound** [comment]
I've finally got round to adding Rey support in commit 87a22f5, to be released shortly. Sorry for the long delay on this - I hope to be able to give Crystal a bit more love in 2021 😄.
