### ISSUE TITLE
Seconds missing 

### ISSUE THREAD

**Issue by dustxs** [warmsound/crystal-face#186]
Seconds is missing. Comes back after pressing Up/Down to see a different screen then back to the home face. Seconds then persists for 5-10sec then disappears again.

**Comment by warmsound** [comment]
@dustxs Which watch model do you have? Older/lower spec watches are unfortunately not able to update the screen once they drop into low power mode (after the 5-10sec you mention).

**Comment by dustxs** [comment]
Thanks for coming back. I have the Swim 2 from late-2019.

**Comment by warmsound** [comment]
The Swim 2 only supports Connect IQ 1.4.x, I'm afraid, so it's unable to show seconds continuously in low power mode.

**Comment by daniele-athome** [comment]
On the Swim 2 the "look at watch" gesture causes the seconds to be displayed again for a few seconds.
