### ISSUE TITLE
Venu 2 support?

### ISSUE THREAD

**Issue by fallingrock** [warmsound/crystal-face#191]
I used this watch face on my VA4 and was disappointed that it's not currently available for my new Venu 2.

Please consider adding the Venu 2 to the supported devices.

If any info or testing is required, I'm happy to help.

**Comment by warmsound** [comment]
@fallingrock, thanks for getting in touch. I hope to add support soon - I'll updated here once I have some progress.

**Comment by fallingrock** [comment]
I know nothing about ciq currently, but I may play around with it.

**Comment by warmsound** [comment]
Well done for getting that far!

Looks like `venu2` is a new larger size, `round-416x416`. There isn't a `resources-*` folder for this device size yet, and the default `resources` folder is actually for `round-240x240`, which doesn't have any of the `AlwaysOn*` fonts, hence the above new build errors.

Because of the new size, this will actually require some design work in Affinity Designer, to decide on the new font sizes and layouts for both the regular and always on views, then generation of all the bitmap fonts, fonts.xml, layout.xml etc.

Even the `venu2s` is a new size, `round-360x360`, so the same applies there.

**Comment by fallingrock** [comment]
Heh, yeah, I know enough to be dangerous.

I figured out the screen size thing ... so I tried copying the round-390x390 directory over to round-416x416.  It didn't have a compile failure, but the simulator ends up just showing a blank watch screen.

**Comment by alexeidrekker** [comment]
Yup. Waiting for the update. This is my favorite watch face. I'm glad there's already an open request as I was about to create one myself.

**Comment by warmsound** [comment]
Thanks everyone for your patience 🤝 . I've started preparing the designs and resources for the new watch sizes, so I hope to be able to release something later this week.

**Comment by fallingrock** [comment]
Considering that Vince is currently the only person contributing to this project, we should keep him well fueled with coffee. 😁

**Comment by warmsound** [comment]
That's resources and layouts done, so will do some testing over the next couple of days, then this will be good for release.

The `venu2s` layout isn't perfect, as the watch really needs an intermediate size of icon and weather icon fonts, which are both hand-generated, so will take some time. So I'll release a separate update for that improvement.

**Comment by fallingrock** [comment]
I'm happy to test if you like.

**Comment by fallingrock** [comment]
Built and side loaded it.  Seems to be working.

I'll let you know.

**Comment by warmsound** [comment]
Wow, that was quick - I've only just built and uploaded the Beta to test. Thanks for your help.

I noticed, while testing on the simulator, that the anti-aliasing looked rough for the data fields at the top of the watchface, when using light themes (other fonts looked fine). It seemed a bit intermittent, so it may just be a simulator glitch.

If all looks OK, then I can release hopefully tomorrow.

**Comment by fallingrock** [comment]
I noticed the watchface isn't quite right in garmin connect ios. Is this normal?

![IMG_A3BD52146FD2-1](https://user-images.githubusercontent.com/4029821/120551023-332fbf80-c3bb-11eb-80d9-c01e05a5f316.jpeg)

Also, I'm not seeing any customizations .. I can't remember if there were any.

**Comment by warmsound** [comment]
IIRC both are effects of sideloading, unfortunately 😢

**Comment by fallingrock** [comment]
I had a serious battery drain last night ... it went from 80% down to 30% while I slept.

The only thing that changed was the watch face.

**Comment by warmsound** [comment]
Thanks for reporting back. Has that battery drain continued, or have things stabilised? Is the watchface dropping into low-power mode OK (with just monochrome time/date/battery showing)?

**Comment by fallingrock** [comment]
Battery life seems to have stabilized. I'll continue to monitor.

**Comment by fallingrock** [comment]
Nope, I was wrong. It went from 79% to 13% overnight. 

I'm switching to the previous watch face to see if it's Crystal or something else.

**Comment by fallingrock** [comment]
Without the crystal watch face, power utilization is normal. 

I'll try switching back to crystal and see how it behaves. 

The watch face I'm using has mostly gray scale colors with a little red accent. I wonder if that has a bearing on the power utilization?

**Comment by fallingrock** [comment]
Seems to be ok now it's dropped 10% in 12 hours.

**Comment by warmsound** [comment]
@fallingrock Thanks for your investigation and updates! Sorry for the delay, as I've been away. It's hard to say if the battery drain was due to some kind of one-time optimisation of the watch face, perhaps related to sideloading, or something completely different! I think we should be good for release, and I'll monitor the user feedback for a while.

**Comment by warmsound** [comment]
@fallingrock I've just released `v2.5.0`, and credited you in the README for your help - thanks again.

I'll try and improve the `venu2s` layout with the intermediate size icon fonts next, assuming no serious issues arise with the release.

**Comment by fallingrock** [comment]
I can't install it. 

"ConnectIQ.NetworkManagerError error 3"

Garmin support says there is a problem with the watch face. 
![image](https://user-images.githubusercontent.com/4029821/121602465-f2fcbc80-ca0c-11eb-8490-d8ab8a9fa3c7.png)

**Comment by alexeidrekker** [comment]
It says it's not on my phone. ![Screenshot_20210610-180105_Connect IQ.png](https://user-images.githubusercontent.com/68187312/121602817-d87b1100-ca15-11eb-9297-0fc0c7be9c1f.png)

**Comment by warmsound** [comment]
@fallingrock, I've tried using the Connect app (not the ConnectIQ app), uninstalled the old watch face, and installed the new version, and this seems to have worked for me (on a vivoactive3). Could you try that?

**Comment by warmsound** [comment]
@alexeidrekker, the Connect IQ store (website) reports Crystal as being compatible with Venu 2S, but the ConnectIQ app does not. I'm not sure if this is a limitation of the app (seems unlikely), something is slow to update, or something else. Does the older Connect app work for you? Or how about Garmin Express on a desktop machine? If you don't have any luck, I'll resume investigation tomorrow, as it's late in the UK now.

**Comment by fallingrock** [comment]
> @fallingrock, I've tried using the Connect app (not the ConnectIQ app), uninstalled the old watch face, and installed the new version, and this seems to have worked for me (on a vivoactive3). Could you try that?

Yes, that got it to install. 

However, the details on the installed watch face are kind of funky. ![image](https://user-images.githubusercontent.com/4029821/121604222-be3e3480-ca0f-11eb-95af-d3bfaac91c18.png)

**Comment by alexeidrekker** [comment]
It has been updated in the store now. Was able to install it.
