### ISSUE TITLE
Forerunner 55 support please.

### ISSUE THREAD

**Issue by ghtalpo** [warmsound/crystal-face#206]
It's similiar to Forerunner 45.

I've made a ugly patch to work on my own. (I'm a newbie here)

Can you make a official support for FR 55?

Thanks.

**Comment by warmsound** [comment]
@ghtalpo, I'm sorry that this is many months late, but I've returned to Crystal, and added support for many watches, including the FR45, in the latest `2.6.0` update. I hope you can still make use of this somehow.
