### ISSUE TITLE
Empty settings

### ISSUE THREAD

**Issue by godcore** [warmsound/crystal-face#43]
First of all, thank you for the great watchface!
My problem is: I don't have any settings available for this watchface both in Garmin connect Android app and in my Garmin Fenix x5 watch. I don't have even "settings" options on device for this particular watchface. What am I doing wrong?

**Comment by warmsound** [comment]
Sorry for the delay in getting back to you, as I was on holiday.

You can't normally change the settings for a 3rd-party (non-Garmin) watch face on the watch itself, but as you say, the settings should be available in the Garmin Connect mobile app. A couple of things to try:

- Can you access the settings for other 3rd-party watch faces in the Garmin Connect mobile app?
- Can you access the settings for Crystal in the Garmin Express desktop app (if you have it available)?

(I'm assuming you'll already have seen this link/know the information provided within, but just in case, here are Garmin's instructions for accessing watch face settings via Garmin Connect:
https://support.garmin.com/faqSearch/en-US/faq/content/SPo0TFvhQO04O36Y5TYRh5)

**Comment by warmsound** [comment]
@godcore, just wondering if you've had any luck finding the settings for Crystal, and customising it the way you want?

**Comment by warmsound** [comment]
Closing, as issue is now old. Please re-open if settings problem occurs again.
