### ISSUE TITLE
Add outdoor temperature data field

### ISSUE THREAD

**Issue by hasselrot** [warmsound/crystal-face#46]
Hi!

Awesome watch face! Only thing im missing is to be able to see the current outdoor temperature.

//Lars

**Comment by warmsound** [comment]
Hi Lars,

Thanks for dropping by, and for your kind words!

Did you mean a feature that reports the local weather? It's been a popular request - not sure why there isn't already an Issue for tracking this! Let's use this one. I'll need to do some investigation, and it's a little more work than some of the smaller feature requests, but I hope to provide it in the near future.

Thanks!

Vince.
