### ISSUE TITLE
Active calories field

### ISSUE THREAD

**Issue by hasselrot** [warmsound/crystal-face#55]
Would be nice to have an option to show only active calories, instead of the total amount.

**Comment by warmsound** [comment]
It doesn't look like this information is available in the Connect IQ API, unfortunately - I can only see a single `calories` value reported. Are you aware of any other third-party watch faces that can display active calories?

**Comment by hasselrot** [comment]
How unfortunate. No I just got my first Garmin watch a few weeks ago.

Thanks for the effort anyway!

**Comment by warmsound** [comment]
No worries!
