### ISSUE TITLE
Weather icon always showing as rectangle on one user's 735xt

### ISSUE THREAD

**Issue by warmsound** [warmsound/crystal-face#89]
Reported by Erica Melton. Happens for different weather conditions, and both day and night. Firmware 9.4

**Comment by warmsound** [comment]
Unable to reproduce, and no further reports in 4 months, so will close for now.

**Comment by rocklobster42195** [comment]
Please reopen.
I also get the square instead of weather incon on my 735xt (v9.4)
Crystal v2.3.2

**Comment by warmsound** [comment]
Issue raised on Garmin forums:
https://ciq.forums.garmin.com/developer/connect-iq/i/bug-reports/custom-subsetted-weather-icon-font-rendering-incorrectly-on-real-735xt

**Comment by warmsound** [comment]
As per the above thread, I'll try modifying the `.fnt` file manually, so that the weather icons use `char id`s of regular ASCII characters.
