### ISSUE TITLE
License

### ISSUE THREAD

**Issue by le-cds** [warmsound/crystal-face#91]
Great work on the watchface! I've been using some of your code to develop my own, which I'd love to push to GitHub. Is there any specific license you're publishing the code under? I feel a little strange publishing code in my repository that I don't know the license of (although I would of course attribute you in the readme file).

**Comment by warmsound** [comment]
Thanks for bringing this to my attention. I've applied to the GNU GPLv3 license to the repo, as I feel this matches the spirit of Crystal most closely. I hope this helps you with your own project - very best of luck with this!

**Comment by le-cds** [comment]
Thanks a lot, it does help. I don't have a problem putting code of such a side project under GPL. [And here it is.](https://github.com/le-cds/connectiq/tree/master/FaceyMcWatchFace), so thanks again. :blush:
