### ISSUE TITLE
Sun Rise & Sun Set time incorrect

### ISSUE THREAD

**Issue by Jaypatadiya** [warmsound/crystal-face#92]
Temperature shows accurate in this watch face but Sunrise and Sunset time always shows incorrectly. Even after recording activity and using GPS. I have noticed that it shows 30 mins behind. For example, watch face shows today's sunset time in Ahmedabad at 05:36 PM while on Google and other websites it shows 06:06 PM. Can anyone help me how to fix this?

**Comment by warmsound** [comment]
Hi Jaypatadiya,

The first thing to check is that your watch has the correct GPS position (try starting an activity recording), as it's used to calculate the sunrise/sunset time. There's every chance that the weather is similar some distance away, but having said that, I suspect this is not the problem.

I notice that Ahmedabad is on India Standard Time, which is UTC +5:30, and it's strange that your offset is exactly 30 mins. The sunrise/sunset time also depends on the time zone offset (`Sys.getClockTime().timeZoneOffset`) returned by the watch, so it's possible that this is wrong for some reason. Are you able to check the current time zone, either on your watch, or in the Garmin Connect mobile app? Are you able to set this manually, just to check whether this is the issue or not?

**Comment by warmsound** [comment]
Closing, as no reply from user. Please re-open as necessary.
